### ISSUE TITLE
Add configurable prefix and suffix for the <title> 

### ISSUE THREAD

**Issue by leroy0211** [sonata-project/SonataSeoBundle#319] opened 2019-01-18 09:47 UTC
## Feature Request

It would be great to have a configurable prefix and suffix for the `<title>` element. 

When you use `->setTitle()` or `->addTitle()` the prefix and suffix will be added to the result. The prefix and suffix should be configured in the configuration but may be overwritten by the user when requesting the `sonata.seo.page` service.

**Comment by core23** [comment] 2019-01-19 17:56
Can you provide a PR @leroy0211 ?

**Comment by core23** [comment] 2020-01-31 09:54
Duplicate of https://github.com/sonata-project/SonataSeoBundle/issues/157

**Closed by core23** 2020-01-31 09:54 UTC
Labels: feature
